### ISSUE TITLE
Layer not working on Amazon Linux 2

### ISSUE THREAD

**Issue by markusahlstrand** [gipsh/aws-calibre-layer#1]
Thanks for publishing this layer!

I tried using it in a node lambda, but they run on the newer VM (amazon linux 2) and it doesn't seem to work.. I'm no good with python, but as far as I understand the X11 packages are not available on the newer VM's. Would it be possible to add the missing packages to the layer?

Thanks!

**Comment by gipsh** [comment]
When you execute the  binary `/opt/ebook-convert` what error is throwing ? 

I need to try it myself on the new vms.

**Comment by markusahlstrand** [comment]
This is the error I get when I try to convert a file from epub -> mobi
```
Command failed: ebook-convert \"/tmp/1599059003173.epub\" \"/tmp/1599059003173.epub.azw3\"
Traceback (most recent call last):
 File \"site.py\", line 77, in main
 File \"site-packages/calibre/ebooks/conversion/cli.py\", line 401, in main
 File \"site-packages/calibre/ebooks/conversion/plumber.py\", line 1275, in run
 File \"site-packages/calibre/ebooks/conversion/plugins/mobi_output.py\", line 312, in convert
 File \"site-packages/calibre/ebooks/mobi/writer2/resources.py\", line 12, in <module>
 File \"site-packages/calibre/ebooks/mobi/utils.py\", line 13, in <module>
 File \"site-packages/calibre/utils/img.py\", line 17, in <module>
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

It seems that other people has run in to similar issues when trying to get calibre on Synology devices and to my understanding this is due to missing X11 packages.

**Comment by gipsh** [comment]
Did you try installing the `amazon linux 2` vm on your host and run the layer locally? 
Probably there are more missing libs.

**Comment by markusahlstrand** [comment]
I'll try settings up an image on ec2. Guessing that the Amazon Linux 2 AMI (HVM) is the same image they use in the lambdas?

**Comment by markusahlstrand** [comment]
I got an ec2 image up and running and have check the following:
- The automatic installer of calibre, the v4 tarball and the v3 tarball all fail with the same error.
- The prerequisites xdg-utils, wget, xz-utils and python ≥ 2.6 all seem available
- GLIBC and gcc versions seems fine.

The error I get is:
Traceback (most recent call last):
  File "site.py", line 75, in main
  File "site-packages/calibre/__init__.py", line 23, in <module>
  File "site-packages/calibre/startup.py", line 156, in <module>
  File "locale.py", line 545, in getdefaultlocale
  File "locale.py", line 477, in _parse_localename
ValueError: unknown locale: UTF-8

**Comment by markusahlstrand** [comment]
Ok.. so it seems to simply be an issue with the default locale being wrong.

Tried what was suggested in this post and it seems to work in my VM: https://www.mobileread.com/forums/showthread.php?t=286960

I'll try adding these environment variable to my lambda code and hopefully the layer works fine.

**Comment by gipsh** [comment]
I tried myself to run the layer on `amazon linux 2 ` vm, and got the same error for libGL. 
Once installed i still throwing errors for Qt. 
Is going to take some time to make it work and im not sure if could be done without hitting the 250MB limit for the layer.

**Comment by markusahlstrand** [comment]
Ok, I installed Qt as part of chrome headless when debugging (https://intoli.com/blog/installing-google-chrome-on-centos/), and maybe that fixed the first part of the issue.. I'll wipe the server and try it again.

**Comment by markusahlstrand** [comment]
Would custom runtimes be a way to get around this issue: https://aws.amazon.com/about-aws/whats-new/2020/08/aws-lambda-supports-custom-runtimes-amazon-linux-2/

**Comment by evangow** [comment]
@markusahlstrand did you ever find a workaround to these issues?

**Comment by markusahlstrand** [comment]
Nope, we are running a docker container as a lambda instead which works well

**Comment by evangow** [comment]
@markusahlstrand any chance you could share the dockerfile for building the container image? Every time I think I might solve the problem, I keep running into different import errors.

**Comment by sveinare** [comment]
> Nope, we are running a docker container as a lambda instead which works well

Do you have the Docker-file to share? Is it still running well?

**Comment by markusahlstrand** [comment]
We haven't used this in this in while, but it was running just fine for over a year:
```
# Define custom function directory
ARG FUNCTION_DIR="/function"

FROM node:12-buster as build-image

# Include global arg in this stage of the build
ARG FUNCTION_DIR

# Install aws-lambda-cpp build dependencies
RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev

# If the dependency is not in package.json uncomment the following line
# RUN npm install aws-lambda-ric

# Copy function code
RUN mkdir -p ${FUNCTION_DIR}
COPY ./* ${FUNCTION_DIR}/

WORKDIR ${FUNCTION_DIR}

RUN npm install

# Grab a fresh slim copy of the image to reduce the final size
FROM node:12-buster-slim

# Include global arg in this stage of the build
ARG FUNCTION_DIR

RUN apt-get update && \
    apt-get install -y \
    cmake \
    x11-utils \ 
    wget \ 
    xz-utils \ 
    curl \
    libnss3-tools \    
    python \
    qpdf

# Install calibre
ENV CALIBRE_INSTALLER_SOURCE_CODE_URL https://raw.githubusercontent.com/kovidgoyal/calibre/v4.23.0/setup/linux-installer.py

RUN wget -O- ${CALIBRE_INSTALLER_SOURCE_CODE_URL} | python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main(install_dir='/opt', isolated=True)" && \
    rm -rf /tmp/calibre-installer-cache

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

ENV QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox --single-process --disable-gpu --disable-dev-shm-usage"
ENV XDG_RUNTIME_DIR="/tmp"

# Copy in the built dependencies
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}

# Uncomment for running on "normal" docker
# CMD ["node", "index.js"]

# Uncommemt for running in lambda
ENTRYPOINT ["/usr/local/bin/npx", "aws-lambda-ric"]
CMD ["index.handler"]
```

It was used as part of a AWS lambda SDK, so might not fit perfectly for you
